### ISSUE TITLE
parallel may breaks output 

### ISSUE THREAD

**Issue by EricDeveaud** [harry-thorpe/piggy#10]
Hello, 

while running piggy with option -t > 1 
we have the output clutered by parallel citation request message

this depends on the distro you use, some distro disable the notice some not. 

it can be solved by using parallel --no-notice in the parallel calls see: http://lists.gnu.org/archive/html/parallel/2013-11/msg00006.html

attached patch fix it.

regards

Eric
[silent_parallel.patch.txt](https://github.com/harry-thorpe/piggy/files/1249273/silent_parallel.patch.txt)

**Comment by harry-thorpe** [comment]
Hi Eric,

Yes I'm aware of this issue, but in my version of parallel the --no-notice tag breaks it. I think the best solution is to follow the citation instructions to remove the message, but I will look into it further.

Thanks,

Harry
