### ISSUE TITLE
out_dir should be created just before run

### ISSUE THREAD

**Issue by EricDeveaud** [harry-thorpe/piggy#11]
hello, 

when piggy is launched with bad option value or non exiting in-dir or .... 
it currently produce an empty outdir.

just creating the out_dir after all checks will solve this

create out_dr after 
check roary_dir
check threads
check nuc_id
check len_id
check method
check dependencies
check in_dir contains gff files

regards

Eric

**Comment by harry-thorpe** [comment]
Hi Eric,

I've sorted this.

Thanks,

Harry
