### ISSUE TITLE
break of "IGR_presence_absence.csv" after 1334 columns 

### ISSUE THREAD

**Issue by rossimk** [harry-thorpe/piggy#19]
We are analyzing more than 1300 genomes using piggy and we have found that the output "IGR_presence_absence.csv" has probably a bug which stops the use of scoary. If you, for example, open the "IGR_presence_absence.csv" in excel after the 1334th column there is a new line. We have tested several times changing dataset but the problem remains.

**Comment by harry-thorpe** [comment]
Hi Mirko,

By my calculations the file should have 1337 columns (14 info + 1323 isolates). I have opened the part of the file you sent via email in a text editor, and it looks OK to me. Unfortunately I cannot open it in excel as I don't have it on my computer, and libreOffice has a small max number of columns so won't open the file.

'wc -l IGR_presence_absence2.csv' also returns 10 lines for the file.

Have you tried in a text editor? What does excel show on the following line, is it just the remaining three columns? Does this happen with every line in the file?

Thanks,

Harry
