### ISSUE TITLE
while(readdir) not consistent amon perl versions

### ISSUE THREAD

**Issue by EricDeveaud** [harry-thorpe/piggy#9]
Hello, 

with perl 5.8.9 piggy is broken due to the following code.

```perl
while(readdir $dh){
	my $file=$_;
```

in perl 5.8.9 (pretty old) but it is the one we use on our cluster. $_ is not set in this context.

tested with newer perl > 5.20 and it's OK

attached simple patch sort out the problem
sorry to lazy to make a pull request

Eric
[readdir_loop.patch.txt](https://github.com/harry-thorpe/piggy/files/1248778/readdir_loop.patch.txt)

**Comment by harry-thorpe** [comment]
Hi Eric,

Thanks for pointing this out. I have updated the code on all readdir calls. Hopefully it should work now.

Thanks,

Harry

**Comment by EricDeveaud** [comment]
thanks
